version: '3.4'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 6FuSQ5HxgHz1
      MYSQL_DATABASE: geek_shopping_product_api
    ports:
      - 3306:3306

  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - 8080:8080

  geekshopping.web:
    image: ${DOCKER_REGISTRY-}geekshoppingweb
    build:
      context: .
      dockerfile: GeekShopping.Web/Dockerfile
    depends_on:
      - geekshopping.productapi

  geekshopping.productapi:
    image: ${DOCKER_REGISTRY-}geekshoppingproductapi
    build:
      context: .
      dockerfile: GeekShopping.ProductAPI/Dockerfile
    depends_on:
      - db
